export interface LeagueTier {
  id: 'bronze' | 'silver' | 'gold' | 'diamond' | 'architect';
  name: string;
  badgeIcon: string;
  accentColor: string;
  borderColor: string;
  minPoints: number;
  perks: string[];
  description: string;
}

export interface BracketMember {
  id: string;
  rank: number;
  name: string;
  username: string;
  collegeOrCompany: string;
  region: string;
  weeklyPoints: number;
  rankChange: number; // +2, -1, 0
  isCurrentUser?: boolean;
  avatarBg: string;
  badges: string[];
  streakDays: number;
}

export interface WeeklyChallenge {
  id: string;
  weekNumber: number;
  title: string;
  category: string;
  prompt: string;
  pointsAwarded: number;
  sampleSubmissionHint: string;
  submissionsCount: number;
}

export interface AchievementBadge {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
  requirement: string;
  isUnlocked: boolean;
  unlockedAt?: string;
  recruiterValue: 'High' | 'Elite' | 'Distinguished';
}

export const LEAGUE_TIERS: LeagueTier[] = [
  {
    id: 'bronze',
    name: 'Bronze AI Engineer',
    badgeIcon: '🥉',
    accentColor: 'from-amber-700/20 to-orange-950/30',
    borderColor: 'border-amber-700/40',
    minPoints: 0,
    perks: ['Access to daily AI Sparks feed', 'Standard interview question pool'],
    description: 'Starting competitive division for all new AIgnite learners.',
  },
  {
    id: 'silver',
    name: 'Silver AI Engineer',
    badgeIcon: '🥈',
    accentColor: 'from-slate-400/20 to-zinc-700/30',
    borderColor: 'border-slate-400/40',
    minPoints: 200,
    perks: ['Unlocks company-specific mock challenges', 'Silver profile badge visible to recruiters'],
    description: 'Consistent practitioners mastering core PyTorch and RAG pipelines.',
  },
  {
    id: 'gold',
    name: 'Gold AI Engineer',
    badgeIcon: '🥇',
    accentColor: 'from-amber-400/20 to-yellow-600/30',
    borderColor: 'border-amber-400/40',
    minPoints: 500,
    perks: ['Direct recruiter talent pool listing', 'Priority speech coach evaluation'],
    description: 'Top 25% percentile demonstrating strong systems trade-off thinking.',
  },
  {
    id: 'diamond',
    name: 'LLM Master',
    badgeIcon: '💎',
    accentColor: 'from-cyan-400/20 to-blue-600/30',
    borderColor: 'border-cyan-400/40',
    minPoints: 1000,
    perks: ['Exclusive frontier lab interview challenges', 'Featured candidate card on recruiter homepage'],
    description: 'Advanced practitioners proficient in distributed training, GQA, and kernel optimization.',
  },
  {
    id: 'architect',
    name: 'AI Architect',
    badgeIcon: '👑',
    accentColor: 'from-primary/25 to-accent/30',
    borderColor: 'border-primary/50',
    minPoints: 2000,
    perks: ['Top 1% National Ranking recognition', 'Fast-track interview invitations from verified partners'],
    description: 'Elite architects capable of designing end-to-end multimodal systems from scratch.',
  },
];

export const INITIAL_BRACKET_MEMBERS: BracketMember[] = [
  {
    id: 'mem-1',
    rank: 1,
    name: 'Aarav Sharma',
    username: 'aarav_sharma',
    collegeOrCompany: 'IIT Bombay',
    region: 'Maharashtra',
    weeklyPoints: 520,
    rankChange: 0,
    avatarBg: 'bg-emerald-500/20 text-emerald-500',
    badges: ['RAG Master', 'TensorRT Specialist'],
    streakDays: 14,
  },
  {
    id: 'mem-2',
    rank: 2,
    name: 'Priya Patel',
    username: 'priya_ml',
    collegeOrCompany: 'BITS Pilani',
    region: 'Rajasthan',
    weeklyPoints: 495,
    rankChange: 2,
    avatarBg: 'bg-primary/20 text-primary',
    badges: ['Agent Architect', 'Vector Wizard'],
    streakDays: 19,
  },
  {
    id: 'mem-3',
    rank: 3,
    name: 'Rohan Deshmukh',
    username: 'rohan_cuda',
    collegeOrCompany: 'IIIT Hyderabad',
    region: 'Telangana',
    weeklyPoints: 460,
    rankChange: 1,
    avatarBg: 'bg-cyan-500/20 text-cyan-500',
    badges: ['CUDA Specialist'],
    streakDays: 11,
  },
  {
    id: 'mem-4',
    rank: 4,
    name: 'Ananya Iyer',
    username: 'ananya_ai',
    collegeOrCompany: 'IIT Madras',
    region: 'Tamil Nadu',
    weeklyPoints: 435,
    rankChange: -2,
    avatarBg: 'bg-purple-500/20 text-purple-500',
    badges: ['RAG Master', 'Prompt Titan'],
    streakDays: 8,
  },
  {
    id: 'mem-5',
    rank: 5,
    name: 'Vaidik (You)',
    username: 'vaidik_ai',
    collegeOrCompany: 'SIH Hackathon Squad',
    region: 'National',
    weeklyPoints: 415,
    rankChange: 3,
    isCurrentUser: true,
    avatarBg: 'bg-primary/30 text-primary',
    badges: ['RAG Master', '7-Day Streak'],
    streakDays: 5,
  },
  {
    id: 'mem-6',
    rank: 6,
    name: 'Kabir Mehta',
    username: 'kabir_llm',
    collegeOrCompany: 'DTU Delhi',
    region: 'Delhi NCR',
    weeklyPoints: 390,
    rankChange: 1,
    avatarBg: 'bg-amber-500/20 text-amber-500',
    badges: ['Vector Wizard'],
    streakDays: 6,
  },
  // Safe Zone
  {
    id: 'mem-7',
    rank: 7,
    name: 'Sneha Roy',
    username: 'sneha_nlp',
    collegeOrCompany: 'Jadavpur University',
    region: 'West Bengal',
    weeklyPoints: 365,
    rankChange: -1,
    avatarBg: 'bg-blue-500/20 text-blue-500',
    badges: ['Prompt Titan'],
    streakDays: 4,
  },
  {
    id: 'mem-8',
    rank: 8,
    name: 'Arjun Nair',
    username: 'arjun_vllm',
    collegeOrCompany: 'NIT Trichy',
    region: 'Tamil Nadu',
    weeklyPoints: 340,
    rankChange: 0,
    avatarBg: 'bg-emerald-500/20 text-emerald-500',
    badges: ['TensorRT Specialist'],
    streakDays: 9,
  },
  {
    id: 'mem-9',
    rank: 9,
    name: 'Devika Menon',
    username: 'devika_cv',
    collegeOrCompany: 'IIT Roorkee',
    region: 'Uttarakhand',
    weeklyPoints: 325,
    rankChange: 4,
    avatarBg: 'bg-pink-500/20 text-pink-500',
    badges: ['CNN Explorer'],
    streakDays: 7,
  },
  {
    id: 'mem-10',
    rank: 10,
    name: 'Aditya Sen',
    username: 'aditya_rl',
    collegeOrCompany: 'IIT Kharagpur',
    region: 'West Bengal',
    weeklyPoints: 310,
    rankChange: -2,
    avatarBg: 'bg-indigo-500/20 text-indigo-500',
    badges: ['Agent Architect'],
    streakDays: 5,
  },
  {
    id: 'mem-11',
    rank: 11,
    name: 'Ishaan Kulkarni',
    username: 'ishaan_k',
    collegeOrCompany: 'COEP Pune',
    region: 'Maharashtra',
    weeklyPoints: 290,
    rankChange: 0,
    avatarBg: 'bg-teal-500/20 text-teal-500',
    badges: [],
    streakDays: 3,
  },
  {
    id: 'mem-12',
    rank: 12,
    name: 'Meera Nambiar',
    username: 'meera_embed',
    collegeOrCompany: 'NIT Calicut',
    region: 'Kerala',
    weeklyPoints: 275,
    rankChange: -3,
    avatarBg: 'bg-cyan-500/20 text-cyan-500',
    badges: ['Vector Wizard'],
    streakDays: 4,
  },
  {
    id: 'mem-13',
    rank: 13,
    name: 'Siddharth Rao',
    username: 'sid_rag',
    collegeOrCompany: 'RVCE Bangalore',
    region: 'Karnataka',
    weeklyPoints: 260,
    rankChange: 2,
    avatarBg: 'bg-violet-500/20 text-violet-500',
    badges: ['RAG Master'],
    streakDays: 6,
  },
  {
    id: 'mem-14',
    rank: 14,
    name: 'Tanvi Gokhale',
    username: 'tanvi_g',
    collegeOrCompany: 'VJTI Mumbai',
    region: 'Maharashtra',
    weeklyPoints: 245,
    rankChange: -1,
    avatarBg: 'bg-amber-500/20 text-amber-500',
    badges: [],
    streakDays: 2,
  },
  {
    id: 'mem-15',
    rank: 15,
    name: 'Harsh Vardhan',
    username: 'harsh_v',
    collegeOrCompany: 'IIT BHU',
    region: 'Uttar Pradesh',
    weeklyPoints: 230,
    rankChange: 0,
    avatarBg: 'bg-rose-500/20 text-rose-500',
    badges: ['Prompt Titan'],
    streakDays: 5,
  },
  {
    id: 'mem-16',
    rank: 16,
    name: 'Nisha Pillai',
    username: 'nisha_ai',
    collegeOrCompany: 'PES University',
    region: 'Karnataka',
    weeklyPoints: 215,
    rankChange: 1,
    avatarBg: 'bg-fuchsia-500/20 text-fuchsia-500',
    badges: [],
    streakDays: 3,
  },
  {
    id: 'mem-17',
    rank: 17,
    name: 'Gaurav Bhatt',
    username: 'gaurav_b',
    collegeOrCompany: 'Thapar University',
    region: 'Punjab',
    weeklyPoints: 200,
    rankChange: -2,
    avatarBg: 'bg-sky-500/20 text-sky-500',
    badges: [],
    streakDays: 4,
  },
  {
    id: 'mem-18',
    rank: 18,
    name: 'Riya Mukherjee',
    username: 'riya_m',
    collegeOrCompany: 'Heritage Institute',
    region: 'West Bengal',
    weeklyPoints: 185,
    rankChange: 3,
    avatarBg: 'bg-emerald-500/20 text-emerald-500',
    badges: [],
    streakDays: 2,
  },
  {
    id: 'mem-19',
    rank: 19,
    name: 'Kunal Joshi',
    username: 'kunal_j',
    collegeOrCompany: 'DA-IICT Gandhinagar',
    region: 'Gujarat',
    weeklyPoints: 170,
    rankChange: -1,
    avatarBg: 'bg-orange-500/20 text-orange-500',
    badges: [],
    streakDays: 1,
  },
  {
    id: 'mem-20',
    rank: 20,
    name: 'Swati Bansal',
    username: 'swati_b',
    collegeOrCompany: 'IGDTUW Delhi',
    region: 'Delhi NCR',
    weeklyPoints: 155,
    rankChange: 0,
    avatarBg: 'bg-pink-500/20 text-pink-500',
    badges: [],
    streakDays: 2,
  },
  {
    id: 'mem-21',
    rank: 21,
    name: 'Manish Tiwari',
    username: 'manish_t',
    collegeOrCompany: 'MANIT Bhopal',
    region: 'Madhya Pradesh',
    weeklyPoints: 140,
    rankChange: -4,
    avatarBg: 'bg-indigo-500/20 text-indigo-500',
    badges: [],
    streakDays: 1,
  },
  {
    id: 'mem-22',
    rank: 22,
    name: 'Pooja Hegde',
    username: 'pooja_h',
    collegeOrCompany: 'BMS College Bangalore',
    region: 'Karnataka',
    weeklyPoints: 125,
    rankChange: 2,
    avatarBg: 'bg-lime-500/20 text-lime-500',
    badges: [],
    streakDays: 3,
  },
  {
    id: 'mem-23',
    rank: 23,
    name: 'Abhishek Saxena',
    username: 'abhi_s',
    collegeOrCompany: 'HBTI Kanpur',
    region: 'Uttar Pradesh',
    weeklyPoints: 110,
    rankChange: -1,
    avatarBg: 'bg-amber-500/20 text-amber-500',
    badges: [],
    streakDays: 1,
  },
  {
    id: 'mem-24',
    rank: 24,
    name: 'Divya Chawla',
    username: 'divya_c',
    collegeOrCompany: 'Chitkara University',
    region: 'Punjab',
    weeklyPoints: 95,
    rankChange: 0,
    avatarBg: 'bg-purple-500/20 text-purple-500',
    badges: [],
    streakDays: 2,
  },
  // Demotion Zone (Bottom 15% - Ranks 25 to 30)
  {
    id: 'mem-25',
    rank: 25,
    name: 'Vikram Sethi',
    username: 'vikram_s',
    collegeOrCompany: 'Amity Noida',
    region: 'Uttar Pradesh',
    weeklyPoints: 75,
    rankChange: -3,
    avatarBg: 'bg-red-500/20 text-red-500',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'mem-26',
    rank: 26,
    name: 'Deepak Choudhary',
    username: 'deepak_c',
    collegeOrCompany: 'LNMIIT Jaipur',
    region: 'Rajasthan',
    weeklyPoints: 60,
    rankChange: -1,
    avatarBg: 'bg-red-500/20 text-red-500',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'mem-27',
    rank: 27,
    name: 'Shreya Das',
    username: 'shreya_d',
    collegeOrCompany: 'KIIT Bhubaneswar',
    region: 'Odisha',
    weeklyPoints: 45,
    rankChange: 0,
    avatarBg: 'bg-red-500/20 text-red-500',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'mem-28',
    rank: 28,
    name: 'Nitin Yadav',
    username: 'nitin_y',
    collegeOrCompany: 'SRM Chennai',
    region: 'Tamil Nadu',
    weeklyPoints: 30,
    rankChange: -2,
    avatarBg: 'bg-red-500/20 text-red-500',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'mem-29',
    rank: 29,
    name: 'Anjali Verma',
    username: 'anjali_v',
    collegeOrCompany: 'Graphic Era Dehradun',
    region: 'Uttarakhand',
    weeklyPoints: 15,
    rankChange: -1,
    avatarBg: 'bg-red-500/20 text-red-500',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'mem-30',
    rank: 30,
    name: 'Rahul Mishra',
    username: 'rahul_m',
    collegeOrCompany: 'Galgotias Greater Noida',
    region: 'Uttar Pradesh',
    weeklyPoints: 0,
    rankChange: 0,
    avatarBg: 'bg-red-500/20 text-red-500',
    badges: [],
    streakDays: 0,
  },
];

export const WEEKLY_LEAGUE_CHALLENGES: WeeklyChallenge[] = [
  {
    id: 'chall-1',
    weekNumber: 36,
    title: 'Design a Sub-100ms Financial SEC Document RAG Pipeline',
    category: 'RAG & Vector Search',
    prompt:
      'Given 100,000 PDF SEC filings, design an end-to-end ingestion and retrieval architecture guaranteeing sub-100ms P95 latency and zero hallucinated numbers.',
    pointsAwarded: 50,
    sampleSubmissionHint:
      'Specify chunking strategy (hybrid sentence-window), vector index (HNSW with pgvector/Milvus), cross-encoder reranker, and numerical guardrail prompt.',
    submissionsCount: 184,
  },
  {
    id: 'chall-2',
    weekNumber: 36,
    title: 'Diagnose and Resolve Distributed PyTorch Deadlock in FSDP',
    category: 'Distributed Systems',
    prompt:
      'A 70B training run with PyTorch Fully Sharded Data Parallel (FSDP-2) freezes during gradient synchronization on 16 H100 nodes. How do you isolate the culprit NCCL barrier?',
    pointsAwarded: 50,
    sampleSubmissionHint:
      'Mention TORCH_DISTRIBUTED_DEBUG=DETAIL, NCCL_DEBUG=INFO, mismatched tensor reduction shapes across ranks, and CPU memory exhaustion.',
    submissionsCount: 122,
  },
  {
    id: 'chall-3',
    weekNumber: 36,
    title: 'Autonomous Tool-Calling Agent with Infinite Loop Protection',
    category: 'Agent Architecture',
    prompt:
      'Construct a ReAct agent framework using Zod/Pydantic schemas with hard state limits that prevents recursive tool-calling hallucination cycles.',
    pointsAwarded: 50,
    sampleSubmissionHint:
      'Describe finite state machine transitions, max iteration guards, schema parsing error feedback injection, and human-in-the-loop escalation.',
    submissionsCount: 209,
  },
  {
    id: 'chall-4',
    weekNumber: 36,
    title: 'Model Quantization Trade-offs: AWQ vs GPTQ vs GGUF',
    category: 'Inference & Quantization',
    prompt:
      'Compare Activation-aware Weight Quantization (AWQ) with GPTQ and GGUF. When is AWQ superior for high-throughput GPU serving in vLLM?',
    pointsAwarded: 50,
    sampleSubmissionHint:
      'Focus on preserving salient 1% activation weights, hardware-friendly matrix packing, and runtime dequantization overhead on Tensor Cores.',
    submissionsCount: 147,
  },
  {
    id: 'chall-5',
    weekNumber: 36,
    title: 'FlashAttention-3 Asynchronous Kernel Specialization Walkthrough',
    category: 'Kernel Engineering',
    prompt:
      'Walk through the producer-consumer warp model in FlashAttention-3 and explain why Hopper TMA completely eliminates register file pressure.',
    pointsAwarded: 50,
    sampleSubmissionHint:
      'Explain direct global memory to shared memory copies via hardware DMA, ping-pong buffering in SRAM, and math warp independence.',
    submissionsCount: 98,
  },
];

export const ACHIEVEMENT_BADGES: AchievementBadge[] = [
  {
    id: 'badge-rag-master',
    name: 'RAG Master',
    category: 'Systems Architecture',
    icon: '🎖️',
    description: 'Flawless assembly of the RAG Pipeline in the Bubble Game with hybrid search and reranker.',
    requirement: 'Complete the RAG Master Bubble Game challenge with 0 errors.',
    isUnlocked: true,
    unlockedAt: 'Yesterday',
    recruiterValue: 'Elite',
  },
  {
    id: 'badge-cuda-ninja',
    name: 'NVIDIA TensorRT Specialist',
    category: 'Hardware Acceleration',
    icon: '🟢',
    description: 'Mastery over CUDA memory hierarchies, TensorRT-LLM engines, and FP8 quantization.',
    requirement: 'Score > 8.0 on the NVIDIA Company Pack Capstone.',
    isUnlocked: true,
    unlockedAt: '2 days ago',
    recruiterValue: 'Elite',
  },
  {
    id: 'badge-agent-architect',
    name: 'Agent Architect',
    category: 'Agent Systems',
    icon: '🤖',
    description: 'Proven ability to build ReAct agentic loops with strict JSON schema tool validation.',
    requirement: 'Complete the OpenAI Pack and pass the Tool Calling Error Hunter challenge.',
    isUnlocked: false,
    recruiterValue: 'Distinguished',
  },
  {
    id: 'badge-flame-streak',
    name: '7-Day Flame Streak',
    category: 'Consistency & Dedication',
    icon: '🔥',
    description: 'Answered the Daily Voice Coach question 7 consecutive mornings at 8:00 AM.',
    requirement: 'Maintain a 7-day daily speaking streak.',
    isUnlocked: false,
    recruiterValue: 'High',
  },
  {
    id: 'badge-vector-wizard',
    name: 'Vector Wizard',
    category: 'Data & Retrieval',
    icon: '🔮',
    description: 'Top evaluation on pgvector HNSW vs IVFFlat indexing tradeoffs under sub-50ms constraints.',
    requirement: 'Solve the AI Decision Simulator Vector Mission with optimal rating.',
    isUnlocked: true,
    unlockedAt: '3 days ago',
    recruiterValue: 'High',
  },
  {
    id: 'badge-prompt-titan',
    name: 'Prompt Titan',
    category: 'LLM Steering',
    icon: '⚡',
    description: 'Zero format errors in structured JSON output generation and safety guardrail prompts.',
    requirement: 'Complete Error Hunter on Structured Outputs without hint.',
    isUnlocked: false,
    recruiterValue: 'High',
  },
];
