export interface LeagueTier {
  id: 'bronze' | 'silver' | 'gold' | 'diamond' | 'architect';
  name: string;
  badgeIcon: string;
  accentColor: string;
  borderColor: string;
  minPoints: number;
  perks: string[];
  description: string;
}

export interface BracketMember {
  id: string;
  rank: number;
  name: string;
  username: string;
  collegeOrCompany: string;
  region: string;
  weeklyPoints: number;
  rankChange: number; // +2, -1, 0
  isCurrentUser?: boolean;
  avatarBg: string;
  badges: string[];
  streakDays: number;
}

export interface WeeklyChallenge {
  id: string;
  weekNumber: number;
  title: string;
  category: string;
  prompt: string;
  pointsAwarded: number;
  sampleSubmissionHint: string;
  submissionsCount: number;
}

export interface AchievementBadge {
  id: string;
  name: string;
  category: string;
  icon: string;
  description: string;
  requirement: string;
  isUnlocked: boolean;
  unlockedAt?: string;
  recruiterValue: 'High' | 'Elite' | 'Distinguished';
}

export interface CollegeLeaderboardEntry {
  rank: number;
  collegeName: string;
  shortName: string;
  city: string;
  state: string;
  totalPoints: number;
  activeStudents: number;
  topTier: string;
  badgeIcon: string;
  avgScore: number;
}

export interface LeaderboardEntry {
  rank: number;
  name: string;
  username: string;
  institutionOrCountry: string;
  streakDays: number;
  scoreXp: number;
  rankChange: number;
  isCurrentUser?: boolean;
  avatarBg: string;
  topBadge: string;
}

// Helper to compute live time remaining to coming Sunday 23:59:59 UTC
export function getTimeRemainingUntilSunday(): {
  formatted: string;
  days: number;
  hours: number;
  minutes: number;
  seconds: number;
  isCycleEndingSoon: boolean;
} {
  const now = new Date();
  const target = new Date(now);
  const dayOfWeek = now.getUTCDay();
  const daysUntilSunday = (7 - dayOfWeek) % 7;
  target.setUTCDate(now.getUTCDate() + daysUntilSunday);
  target.setUTCHours(23, 59, 59, 999);

  const diff = Math.max(0, target.getTime() - now.getTime());
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  const hours = Math.floor((diff / (1000 * 60 * 60)) % 24);
  const minutes = Math.floor((diff / (1000 * 60)) % 60);
  const seconds = Math.floor((diff / 1000) % 60);

  const formatted = `${days}d ${hours}h ${minutes}m (Ends Sunday 23:59 UTC)`;
  return {
    formatted,
    days,
    hours,
    minutes,
    seconds,
    isCycleEndingSoon: days === 0 && hours < 12,
  };
}

export const LEAGUE_TIERS: LeagueTier[] = [
  {
    id: 'bronze',
    name: 'Bronze AI Engineer',
    badgeIcon: '🥉',
    accentColor: 'from-amber-700/20 to-orange-950/30',
    borderColor: 'border-amber-700/40',
    minPoints: 0,
    perks: ['Access to daily AI Sparks feed', 'Standard interview question pool'],
    description: 'Starting competitive division for all new AIgnite learners.',
  },
  {
    id: 'silver',
    name: 'Silver AI Engineer',
    badgeIcon: '🥈',
    accentColor: 'from-slate-400/20 to-zinc-700/30',
    borderColor: 'border-slate-400/40',
    minPoints: 200,
    perks: ['Unlocks company-specific mock challenges', 'Silver profile badge visible to recruiters'],
    description: 'Consistent practitioners mastering core PyTorch and RAG pipelines.',
  },
  {
    id: 'gold',
    name: 'Gold AI Engineer',
    badgeIcon: '🥇',
    accentColor: 'from-amber-400/20 to-yellow-600/30',
    borderColor: 'border-amber-400/40',
    minPoints: 500,
    perks: ['Direct recruiter talent pool listing', 'Priority speech coach evaluation'],
    description: 'Top 25% percentile demonstrating strong systems trade-off thinking.',
  },
  {
    id: 'diamond',
    name: 'LLM Master',
    badgeIcon: '💎',
    accentColor: 'from-cyan-400/20 to-blue-600/30',
    borderColor: 'border-cyan-400/40',
    minPoints: 1000,
    perks: ['Exclusive frontier lab interview challenges', 'Featured candidate card on recruiter homepage'],
    description: 'Advanced practitioners proficient in distributed training, GQA, and kernel optimization.',
  },
  {
    id: 'architect',
    name: 'AI Architect',
    badgeIcon: '👑',
    accentColor: 'from-primary/25 to-accent/30',
    borderColor: 'border-primary/50',
    minPoints: 2000,
    perks: ['Top 1% National Ranking recognition', 'Fast-track interview invitations from verified partners'],
    description: 'Elite architects capable of designing end-to-end multimodal systems from scratch.',
  },
];

// 30-Candidate Weekly Cohort Bracket for Silver Division
export const INITIAL_BRACKET_MEMBERS: BracketMember[] = [
  {
    id: 'bracket-01',
    rank: 1,
    name: 'Devansh Kulkarni',
    username: 'devansh_ai',
    collegeOrCompany: 'IIT Bombay',
    region: 'Maharashtra',
    weeklyPoints: 620,
    rankChange: 2,
    avatarBg: 'bg-amber-500/20 text-amber-600 dark:text-amber-400',
    badges: ['CUDA Specialist', 'RAG Master'],
    streakDays: 16,
  },
  {
    id: 'bracket-02',
    rank: 2,
    name: 'Neha Singhania',
    username: 'neha_nlp',
    collegeOrCompany: 'BITS Pilani',
    region: 'Rajasthan',
    weeklyPoints: 580,
    rankChange: 1,
    avatarBg: 'bg-purple-500/20 text-purple-600 dark:text-purple-400',
    badges: ['Agent Architect', 'Vector Wizard'],
    streakDays: 14,
  },
  {
    id: 'bracket-03',
    rank: 3,
    name: 'Rohan Deshmukh',
    username: 'rohan_systems',
    collegeOrCompany: 'COEP Pune',
    region: 'Maharashtra',
    weeklyPoints: 510,
    rankChange: -1,
    avatarBg: 'bg-blue-500/20 text-blue-600 dark:text-blue-400',
    badges: ['TensorRT Pro'],
    streakDays: 11,
  },
  {
    id: 'bracket-04',
    rank: 4,
    name: 'Ananya Verma',
    username: 'ananya_v',
    collegeOrCompany: 'IIIT Hyderabad',
    region: 'Telangana',
    weeklyPoints: 460,
    rankChange: 3,
    avatarBg: 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400',
    badges: ['Prompt Titan'],
    streakDays: 9,
  },
  {
    id: 'bracket-05',
    rank: 5,
    name: 'Vaidik (You)',
    username: 'vaidik_learner',
    collegeOrCompany: 'AI Engineering Campus',
    region: 'India',
    weeklyPoints: 415,
    rankChange: 4,
    isCurrentUser: true,
    avatarBg: 'bg-primary/20 text-primary',
    badges: ['7-Day Streak', 'RAG Master'],
    streakDays: 7,
  },
  {
    id: 'bracket-06',
    rank: 6,
    name: 'Kavya Subramaniam',
    username: 'kavya_s',
    collegeOrCompany: 'NIT Trichy',
    region: 'Tamil Nadu',
    weeklyPoints: 390,
    rankChange: 1,
    avatarBg: 'bg-rose-500/20 text-rose-600 dark:text-rose-400',
    badges: ['Vector Wizard'],
    streakDays: 8,
  },
  {
    id: 'bracket-07',
    rank: 7,
    name: 'Aditya Sen',
    username: 'aditya_ml',
    collegeOrCompany: 'IIT Delhi',
    region: 'Delhi-NCR',
    weeklyPoints: 370,
    rankChange: -2,
    avatarBg: 'bg-cyan-500/20 text-cyan-600 dark:text-cyan-400',
    badges: ['CUDA Specialist'],
    streakDays: 6,
  },
  {
    id: 'bracket-08',
    rank: 8,
    name: 'Tanvi Iyer',
    username: 'tanvi_ai',
    collegeOrCompany: 'RVCE Bengaluru',
    region: 'Karnataka',
    weeklyPoints: 355,
    rankChange: 0,
    avatarBg: 'bg-indigo-500/20 text-indigo-600 dark:text-indigo-400',
    badges: ['Prompt Titan'],
    streakDays: 10,
  },
  {
    id: 'bracket-09',
    rank: 9,
    name: 'Harsh Vardhan',
    username: 'harsh_v',
    collegeOrCompany: 'DTU Delhi',
    region: 'Delhi-NCR',
    weeklyPoints: 340,
    rankChange: -1,
    avatarBg: 'bg-amber-600/20 text-amber-700 dark:text-amber-300',
    badges: ['RAG Master'],
    streakDays: 5,
  },
  {
    id: 'bracket-10',
    rank: 10,
    name: 'Meera Nair',
    username: 'meera_n',
    collegeOrCompany: 'NIT Calicut',
    region: 'Kerala',
    weeklyPoints: 325,
    rankChange: 2,
    avatarBg: 'bg-teal-500/20 text-teal-600 dark:text-teal-400',
    badges: ['Agent Architect'],
    streakDays: 7,
  },
  {
    id: 'bracket-11',
    rank: 11,
    name: 'Siddharth Pillai',
    username: 'sid_p',
    collegeOrCompany: 'IIT Madras',
    region: 'Tamil Nadu',
    weeklyPoints: 310,
    rankChange: 0,
    avatarBg: 'bg-violet-500/20 text-violet-600 dark:text-violet-400',
    badges: ['Vector Wizard'],
    streakDays: 4,
  },
  {
    id: 'bracket-12',
    rank: 12,
    name: 'Ishita Bansal',
    username: 'ishita_b',
    collegeOrCompany: 'Thapar Institute',
    region: 'Punjab',
    weeklyPoints: 295,
    rankChange: -3,
    avatarBg: 'bg-pink-500/20 text-pink-600 dark:text-pink-400',
    badges: ['Prompt Titan'],
    streakDays: 6,
  },
  {
    id: 'bracket-13',
    rank: 13,
    name: 'Manish Pandey',
    username: 'manish_p',
    collegeOrCompany: 'IIT Roorkee',
    region: 'Uttarakhand',
    weeklyPoints: 280,
    rankChange: 1,
    avatarBg: 'bg-lime-500/20 text-lime-700 dark:text-lime-300',
    badges: ['CUDA Specialist'],
    streakDays: 5,
  },
  {
    id: 'bracket-14',
    rank: 14,
    name: 'Pooja Reddy',
    username: 'pooja_r',
    collegeOrCompany: 'CBIT Hyderabad',
    region: 'Telangana',
    weeklyPoints: 270,
    rankChange: -1,
    avatarBg: 'bg-emerald-600/20 text-emerald-700 dark:text-emerald-300',
    badges: ['RAG Master'],
    streakDays: 4,
  },
  {
    id: 'bracket-15',
    rank: 15,
    name: 'Arjun Mehta',
    username: 'arjun_m',
    collegeOrCompany: 'VJTI Mumbai',
    region: 'Maharashtra',
    weeklyPoints: 260,
    rankChange: 2,
    avatarBg: 'bg-blue-600/20 text-blue-700 dark:text-blue-300',
    badges: ['Vector Wizard'],
    streakDays: 6,
  },
  {
    id: 'bracket-16',
    rank: 16,
    name: 'Shreya Ghosh',
    username: 'shreya_g',
    collegeOrCompany: 'Jadavpur University',
    region: 'West Bengal',
    weeklyPoints: 250,
    rankChange: 0,
    avatarBg: 'bg-orange-500/20 text-orange-600 dark:text-orange-400',
    badges: ['Prompt Titan'],
    streakDays: 3,
  },
  {
    id: 'bracket-17',
    rank: 17,
    name: 'Gaurav Joshi',
    username: 'gaurav_j',
    collegeOrCompany: 'VNIT Nagpur',
    region: 'Maharashtra',
    weeklyPoints: 240,
    rankChange: -2,
    avatarBg: 'bg-zinc-500/20 text-zinc-700 dark:text-zinc-300',
    badges: ['RAG Master'],
    streakDays: 4,
  },
  {
    id: 'bracket-18',
    rank: 18,
    name: 'Swati Ranganathan',
    username: 'swati_r',
    collegeOrCompany: 'PSG Tech',
    region: 'Tamil Nadu',
    weeklyPoints: 230,
    rankChange: 1,
    avatarBg: 'bg-purple-600/20 text-purple-700 dark:text-purple-300',
    badges: ['CUDA Specialist'],
    streakDays: 5,
  },
  {
    id: 'bracket-19',
    rank: 19,
    name: 'Kunal Saxena',
    username: 'kunal_s',
    collegeOrCompany: 'IIT Kanpur',
    region: 'Uttar Pradesh',
    weeklyPoints: 220,
    rankChange: -1,
    avatarBg: 'bg-cyan-600/20 text-cyan-700 dark:text-cyan-300',
    badges: ['Vector Wizard'],
    streakDays: 3,
  },
  {
    id: 'bracket-20',
    rank: 20,
    name: 'Ritu Chawla',
    username: 'ritu_c',
    collegeOrCompany: 'NSUT Delhi',
    region: 'Delhi-NCR',
    weeklyPoints: 210,
    rankChange: 0,
    avatarBg: 'bg-amber-500/20 text-amber-600 dark:text-amber-400',
    badges: ['Prompt Titan'],
    streakDays: 2,
  },
  {
    id: 'bracket-21',
    rank: 21,
    name: 'Naveen Kumar',
    username: 'naveen_k',
    collegeOrCompany: 'NIT Warangal',
    region: 'Telangana',
    weeklyPoints: 205,
    rankChange: 1,
    avatarBg: 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400',
    badges: ['RAG Master'],
    streakDays: 3,
  },
  {
    id: 'bracket-22',
    rank: 22,
    name: 'Deepika Sen',
    username: 'deepika_s',
    collegeOrCompany: 'IIIT Delhi',
    region: 'Delhi-NCR',
    weeklyPoints: 195,
    rankChange: -2,
    avatarBg: 'bg-rose-600/20 text-rose-700 dark:text-rose-300',
    badges: ['Vector Wizard'],
    streakDays: 4,
  },
  {
    id: 'bracket-23',
    rank: 23,
    name: 'Prateek Mishra',
    username: 'prateek_m',
    collegeOrCompany: 'IIT Kharagpur',
    region: 'West Bengal',
    weeklyPoints: 185,
    rankChange: 0,
    avatarBg: 'bg-indigo-600/20 text-indigo-700 dark:text-indigo-300',
    badges: ['CUDA Specialist'],
    streakDays: 2,
  },
  {
    id: 'bracket-24',
    rank: 24,
    name: 'Simran Walia',
    username: 'simran_w',
    collegeOrCompany: 'PEC Chandigarh',
    region: 'Chandigarh',
    weeklyPoints: 175,
    rankChange: -1,
    avatarBg: 'bg-teal-600/20 text-teal-700 dark:text-teal-300',
    badges: ['Prompt Titan'],
    streakDays: 3,
  },
  {
    id: 'bracket-25',
    rank: 25,
    name: 'Rahul Kadam',
    username: 'rahul_k',
    collegeOrCompany: 'SPIT Mumbai',
    region: 'Maharashtra',
    weeklyPoints: 155,
    rankChange: -3,
    avatarBg: 'bg-red-500/20 text-red-600 dark:text-red-400',
    badges: ['RAG Master'],
    streakDays: 1,
  },
  {
    id: 'bracket-26',
    rank: 26,
    name: 'Divya Nambiar',
    username: 'divya_n',
    collegeOrCompany: 'GEC Thrissur',
    region: 'Kerala',
    weeklyPoints: 140,
    rankChange: -2,
    avatarBg: 'bg-orange-600/20 text-orange-700 dark:text-orange-300',
    badges: [],
    streakDays: 1,
  },
  {
    id: 'bracket-27',
    rank: 27,
    name: 'Tushar Gupta',
    username: 'tushar_g',
    collegeOrCompany: 'MANIT Bhopal',
    region: 'Madhya Pradesh',
    weeklyPoints: 125,
    rankChange: -1,
    avatarBg: 'bg-yellow-600/20 text-yellow-700 dark:text-yellow-300',
    badges: [],
    streakDays: 1,
  },
  {
    id: 'bracket-28',
    rank: 28,
    name: 'Aishwarya Roy',
    username: 'aishwarya_r',
    collegeOrCompany: 'IIEST Shibpur',
    region: 'West Bengal',
    weeklyPoints: 110,
    rankChange: -4,
    avatarBg: 'bg-purple-500/20 text-purple-600 dark:text-purple-400',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'bracket-29',
    rank: 29,
    name: 'Varun Bhat',
    username: 'varun_b',
    collegeOrCompany: 'BMSCE Bengaluru',
    region: 'Karnataka',
    weeklyPoints: 95,
    rankChange: -2,
    avatarBg: 'bg-blue-500/20 text-blue-600 dark:text-blue-400',
    badges: [],
    streakDays: 0,
  },
  {
    id: 'bracket-30',
    rank: 30,
    name: 'Aakash Solanki',
    username: 'aakash_s',
    collegeOrCompany: 'LD College Ahmedabad',
    region: 'Gujarat',
    weeklyPoints: 80,
    rankChange: -5,
    avatarBg: 'bg-zinc-600/20 text-zinc-700 dark:text-zinc-300',
    badges: [],
    streakDays: 0,
  },
];

// Production Weekly AI Challenges
export const WEEKLY_LEAGUE_CHALLENGES: WeeklyChallenge[] = [
  {
    id: 'challenge-flashattn',
    weekNumber: 37,
    title: 'FlashAttention-3 TMA Async Pipeline',
    category: 'Hardware Acceleration',
    prompt: 'Explain how FlashAttention-3 avoids HBM bandwidth bottlenecks on NVIDIA Hopper (H100). What role do asynchronous TMA (Tensor Memory Accelerator) and Warp Specialization play in overlapping FP8 GEMM computations with memory loads?',
    pointsAwarded: 50,
    sampleSubmissionHint: 'Mention how TMA copies directly between global memory and shared memory without register file staging, and how warp groups are decoupled into producer and consumer roles.',
    submissionsCount: 142,
  },
  {
    id: 'challenge-speculative',
    weekNumber: 37,
    title: 'Speculative Decoding Draft Engine',
    category: 'Inference Systems',
    prompt: 'Design a speculative decoding pipeline with a small draft model (e.g. 1B) and target model (e.g. 70B). How do you formulate the acceptance probability formula using target and draft logits without altering the output distribution?',
    pointsAwarded: 50,
    sampleSubmissionHint: 'Explain the modified rejection sampling threshold: min(1, P(x)/Q(x)), and explain how tree-based KV verification amortizes verification latency.',
    submissionsCount: 98,
  },
  {
    id: 'challenge-agent-schema',
    weekNumber: 37,
    title: 'ReAct Agent Strict Tool Calling Guardrails',
    category: 'Autonomous Agents',
    prompt: 'How do you engineer deterministic JSON Schema tool calling in LangGraph or OpenAI function calling loops to prevent hallucinations when handling nested arguments and error recovery?',
    pointsAwarded: 50,
    sampleSubmissionHint: 'Discuss Pydantic schema validation, constrained decoding masks over vocab tokens, and structured reflection nodes on parse exceptions.',
    submissionsCount: 115,
  },
  {
    id: 'challenge-rag-rerank',
    weekNumber: 37,
    title: 'Hybrid Lexical & Dense Vector Cross-Encoder Reranking',
    category: 'Retrieval Systems',
    prompt: 'Compare reciprocal rank fusion (RRF) with cross-encoder re-ranking in a hybrid search pipeline (BM25 + pgvector HNSW). When does bi-encoder cosine similarity fail, and why does cross-encoder cross-attention rescue top-5 precision?',
    pointsAwarded: 50,
    sampleSubmissionHint: 'Discuss bi-encoder late interaction vs full cross-attention token comparison, latency vs precision trade-offs, and reciprocal rank fusion constant k=60.',
    submissionsCount: 84,
  },
  {
    id: 'challenge-lora-merge',
    weekNumber: 37,
    title: 'LoRA Weight Merging without Catastrophic Forgetting',
    category: 'Fine-Tuning & Optimization',
    prompt: 'When merging multiple Low-Rank Adaptation (LoRA) adapters into a base foundation model via TIES or DARE merging, how do you resolve gradient interference and sign conflicts across weight matrices?',
    pointsAwarded: 50,
    sampleSubmissionHint: 'Explain parameter delta isolation, trimming low-magnitude deltas, resolving parameter sign conflicts via majority voting, and scaling with rescale factors.',
    submissionsCount: 67,
  },
];

// Top Engineering Colleges Leaderboard
export const TOP_COLLEGES_ROSTER: CollegeLeaderboardEntry[] = [
  {
    rank: 1,
    collegeName: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    city: 'Mumbai',
    state: 'Maharashtra',
    totalPoints: 84200,
    activeStudents: 142,
    topTier: 'AI Architect',
    badgeIcon: '👑',
    avgScore: 9.2,
  },
  {
    rank: 2,
    collegeName: 'Birla Institute of Technology and Science, Pilani',
    shortName: 'BITS Pilani',
    city: 'Pilani',
    state: 'Rajasthan',
    totalPoints: 78450,
    activeStudents: 128,
    topTier: 'AI Architect',
    badgeIcon: '👑',
    avgScore: 9.0,
  },
  {
    rank: 3,
    collegeName: 'International Institute of Information Technology, Hyderabad',
    shortName: 'IIIT Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    totalPoints: 74100,
    activeStudents: 115,
    topTier: 'AI Architect',
    badgeIcon: '👑',
    avgScore: 9.1,
  },
  {
    rank: 4,
    collegeName: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    totalPoints: 69800,
    activeStudents: 110,
    topTier: 'LLM Master',
    badgeIcon: '💎',
    avgScore: 8.9,
  },
  {
    rank: 5,
    collegeName: 'Indian Institute of Technology Madras',
    shortName: 'IIT Madras',
    city: 'Chennai',
    state: 'Tamil Nadu',
    totalPoints: 66350,
    activeStudents: 104,
    topTier: 'LLM Master',
    badgeIcon: '💎',
    avgScore: 8.8,
  },
  {
    rank: 6,
    collegeName: 'National Institute of Technology Karnataka',
    shortName: 'NIT Surathkal',
    city: 'Mangaluru',
    state: 'Karnataka',
    totalPoints: 58900,
    activeStudents: 92,
    topTier: 'LLM Master',
    badgeIcon: '💎',
    avgScore: 8.7,
  },
  {
    rank: 7,
    collegeName: 'Delhi Technological University',
    shortName: 'DTU Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    totalPoints: 52400,
    activeStudents: 88,
    topTier: 'Gold AI Engineer',
    badgeIcon: '🥇',
    avgScore: 8.5,
  },
  {
    rank: 8,
    collegeName: 'R.V. College of Engineering',
    shortName: 'RVCE Bengaluru',
    city: 'Bengaluru',
    state: 'Karnataka',
    totalPoints: 47600,
    activeStudents: 79,
    topTier: 'Gold AI Engineer',
    badgeIcon: '🥇',
    avgScore: 8.4,
  },
  {
    rank: 9,
    collegeName: 'College of Engineering, Pune',
    shortName: 'COEP Tech',
    city: 'Pune',
    state: 'Maharashtra',
    totalPoints: 42100,
    activeStudents: 71,
    topTier: 'Gold AI Engineer',
    badgeIcon: '🥇',
    avgScore: 8.3,
  },
  {
    rank: 10,
    collegeName: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT Trichy',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    totalPoints: 39800,
    activeStudents: 66,
    topTier: 'Gold AI Engineer',
    badgeIcon: '🥇',
    avgScore: 8.2,
  },
];

// Multi-Scope Rosters for Regional, National, and International Standings
export const REGIONAL_LEADERBOARD_ROSTER: LeaderboardEntry[] = [
  {
    rank: 1,
    name: 'Aarav Sharma',
    username: 'aarav_sharma',
    institutionOrCountry: 'IIT Bombay (Maharashtra)',
    streakDays: 28,
    scoreXp: 2420,
    rankChange: 0,
    avatarBg: 'bg-amber-500/20 text-amber-700 dark:text-amber-300',
    topBadge: 'Kernel & TensorRT Specialist',
  },
  {
    rank: 2,
    name: 'Devansh Kulkarni',
    username: 'devansh_ai',
    institutionOrCountry: 'IIT Bombay (Maharashtra)',
    streakDays: 16,
    scoreXp: 1840,
    rankChange: 2,
    avatarBg: 'bg-emerald-500/20 text-emerald-700 dark:text-emerald-300',
    topBadge: 'CUDA Specialist',
  },
  {
    rank: 3,
    name: 'Rohan Deshmukh',
    username: 'rohan_systems',
    institutionOrCountry: 'COEP Pune (Maharashtra)',
    streakDays: 14,
    scoreXp: 1620,
    rankChange: 1,
    avatarBg: 'bg-blue-500/20 text-blue-700 dark:text-blue-300',
    topBadge: 'TensorRT Pro',
  },
  {
    rank: 4,
    name: 'Arjun Mehta',
    username: 'arjun_m',
    institutionOrCountry: 'VJTI Mumbai (Maharashtra)',
    streakDays: 12,
    scoreXp: 1490,
    rankChange: -1,
    avatarBg: 'bg-purple-500/20 text-purple-700 dark:text-purple-300',
    topBadge: 'Vector Wizard',
  },
  {
    rank: 5,
    name: 'Gaurav Joshi',
    username: 'gaurav_j',
    institutionOrCountry: 'VNIT Nagpur (Maharashtra)',
    streakDays: 11,
    scoreXp: 1380,
    rankChange: 3,
    avatarBg: 'bg-rose-500/20 text-rose-700 dark:text-rose-300',
    topBadge: 'RAG Master',
  },
  {
    rank: 6,
    name: 'Rahul Kadam',
    username: 'rahul_k',
    institutionOrCountry: 'SPIT Mumbai (Maharashtra)',
    streakDays: 9,
    scoreXp: 1190,
    rankChange: -2,
    avatarBg: 'bg-cyan-500/20 text-cyan-700 dark:text-cyan-300',
    topBadge: 'Prompt Titan',
  },
  {
    rank: 7,
    name: 'Tanvi Shah',
    username: 'tanvi_s',
    institutionOrCountry: 'PICT Pune (Maharashtra)',
    streakDays: 8,
    scoreXp: 980,
    rankChange: 1,
    avatarBg: 'bg-indigo-500/20 text-indigo-700 dark:text-indigo-300',
    topBadge: 'Agent Architect',
  },
  {
    rank: 8,
    name: 'Sanket Patil',
    username: 'sanket_p',
    institutionOrCountry: 'WCE Sangli (Maharashtra)',
    streakDays: 7,
    scoreXp: 860,
    rankChange: 0,
    avatarBg: 'bg-amber-600/20 text-amber-800 dark:text-amber-200',
    topBadge: 'Vector Wizard',
  },
];

export const NATIONAL_LEADERBOARD_ROSTER: LeaderboardEntry[] = [
  {
    rank: 1,
    name: 'Aarav Sharma',
    username: 'aarav_sharma',
    institutionOrCountry: 'IIT Bombay',
    streakDays: 28,
    scoreXp: 2420,
    rankChange: 0,
    avatarBg: 'bg-amber-500/20 text-amber-700 dark:text-amber-300',
    topBadge: 'Kernel & TensorRT Specialist',
  },
  {
    rank: 2,
    name: 'Priya Patel',
    username: 'priya_ml',
    institutionOrCountry: 'BITS Pilani',
    streakDays: 24,
    scoreXp: 2310,
    rankChange: 1,
    avatarBg: 'bg-purple-500/20 text-purple-700 dark:text-purple-300',
    topBadge: 'Agent Architect',
  },
  {
    rank: 3,
    name: 'Vikramaditya Rao',
    username: 'vikram_ann',
    institutionOrCountry: 'NIT Surathkal',
    streakDays: 19,
    scoreXp: 1980,
    rankChange: -1,
    avatarBg: 'bg-blue-500/20 text-blue-700 dark:text-blue-300',
    topBadge: 'Vector Wizard',
  },
  {
    rank: 4,
    name: 'Ananya Verma',
    username: 'ananya_v',
    institutionOrCountry: 'IIIT Hyderabad',
    streakDays: 18,
    scoreXp: 1890,
    rankChange: 2,
    avatarBg: 'bg-emerald-500/20 text-emerald-700 dark:text-emerald-300',
    topBadge: 'Distributed Training',
  },
  {
    rank: 5,
    name: 'Devansh Kulkarni',
    username: 'devansh_ai',
    institutionOrCountry: 'IIT Bombay',
    streakDays: 16,
    scoreXp: 1840,
    rankChange: 0,
    avatarBg: 'bg-cyan-500/20 text-cyan-700 dark:text-cyan-300',
    topBadge: 'CUDA Specialist',
  },
  {
    rank: 6,
    name: 'Aditya Sen',
    username: 'aditya_ml',
    institutionOrCountry: 'IIT Delhi',
    streakDays: 15,
    scoreXp: 1720,
    rankChange: -2,
    avatarBg: 'bg-rose-500/20 text-rose-700 dark:text-rose-300',
    topBadge: 'Prompt Titan',
  },
  {
    rank: 7,
    name: 'Siddharth Pillai',
    username: 'sid_p',
    institutionOrCountry: 'IIT Madras',
    streakDays: 14,
    scoreXp: 1640,
    rankChange: 1,
    avatarBg: 'bg-indigo-500/20 text-indigo-700 dark:text-indigo-300',
    topBadge: 'RAG Master',
  },
  {
    rank: 8,
    name: 'Harsh Vardhan',
    username: 'harsh_v',
    institutionOrCountry: 'DTU Delhi',
    streakDays: 13,
    scoreXp: 1530,
    rankChange: 0,
    avatarBg: 'bg-teal-500/20 text-teal-700 dark:text-teal-300',
    topBadge: 'Agent Architect',
  },
  {
    rank: 9,
    name: 'Tanvi Iyer',
    username: 'tanvi_ai',
    institutionOrCountry: 'RVCE Bengaluru',
    streakDays: 12,
    scoreXp: 1460,
    rankChange: 3,
    avatarBg: 'bg-pink-500/20 text-pink-700 dark:text-pink-300',
    topBadge: 'Vector Wizard',
  },
  {
    rank: 10,
    name: 'Kavya Subramaniam',
    username: 'kavya_s',
    institutionOrCountry: 'NIT Trichy',
    streakDays: 11,
    scoreXp: 1390,
    rankChange: -1,
    avatarBg: 'bg-amber-600/20 text-amber-800 dark:text-amber-200',
    topBadge: 'TensorRT Pro',
  },
];

export const INTERNATIONAL_LEADERBOARD_ROSTER: LeaderboardEntry[] = [
  {
    rank: 1,
    name: 'Elena Rostova',
    username: 'elena_ai',
    institutionOrCountry: 'Stanford University (USA)',
    streakDays: 34,
    scoreXp: 3120,
    rankChange: 0,
    avatarBg: 'bg-rose-500/20 text-rose-700 dark:text-rose-300',
    topBadge: 'Frontier Post-Training',
  },
  {
    rank: 2,
    name: 'Julian Vance',
    username: 'julian_v',
    institutionOrCountry: 'MIT CSAIL (USA)',
    streakDays: 31,
    scoreXp: 2940,
    rankChange: 1,
    avatarBg: 'bg-indigo-500/20 text-indigo-700 dark:text-indigo-300',
    topBadge: 'FlashAttention Contributor',
  },
  {
    rank: 3,
    name: 'Aarav Sharma',
    username: 'aarav_sharma',
    institutionOrCountry: 'IIT Bombay (India)',
    streakDays: 28,
    scoreXp: 2420,
    rankChange: 2,
    avatarBg: 'bg-amber-500/20 text-amber-700 dark:text-amber-300',
    topBadge: 'Kernel & TensorRT Specialist',
  },
  {
    rank: 4,
    name: 'Chen Wei',
    username: 'chen_w',
    institutionOrCountry: 'Tsinghua University (China)',
    streakDays: 26,
    scoreXp: 2380,
    rankChange: -1,
    avatarBg: 'bg-cyan-500/20 text-cyan-700 dark:text-cyan-300',
    topBadge: 'Quantization & AWQ Master',
  },
  {
    rank: 5,
    name: 'Priya Patel',
    username: 'priya_ml',
    institutionOrCountry: 'BITS Pilani (India)',
    streakDays: 24,
    scoreXp: 2310,
    rankChange: 1,
    avatarBg: 'bg-purple-500/20 text-purple-700 dark:text-purple-300',
    topBadge: 'Agent Architect',
  },
  {
    rank: 6,
    name: 'Sophie Müller',
    username: 'sophie_m',
    institutionOrCountry: 'ETH Zurich (Switzerland)',
    streakDays: 23,
    scoreXp: 2190,
    rankChange: 0,
    avatarBg: 'bg-blue-500/20 text-blue-700 dark:text-blue-300',
    topBadge: 'Robotics & Embodied AI',
  },
  {
    rank: 7,
    name: 'Marcus Thorne',
    username: 'marcus_t',
    institutionOrCountry: 'University of Cambridge (UK)',
    streakDays: 21,
    scoreXp: 2050,
    rankChange: -2,
    avatarBg: 'bg-emerald-500/20 text-emerald-700 dark:text-emerald-300',
    topBadge: 'Speculative Decoding Specialist',
  },
  {
    rank: 8,
    name: 'Lin Zhihao',
    username: 'lin_zh',
    institutionOrCountry: 'NUS (Singapore)',
    streakDays: 20,
    scoreXp: 2010,
    rankChange: 2,
    avatarBg: 'bg-teal-500/20 text-teal-700 dark:text-teal-300',
    topBadge: 'RAG Pipeline Architect',
  },
  {
    rank: 9,
    name: 'Vikramaditya Rao',
    username: 'vikram_ann',
    institutionOrCountry: 'NIT Surathkal (India)',
    streakDays: 19,
    scoreXp: 1980,
    rankChange: -1,
    avatarBg: 'bg-blue-600/20 text-blue-800 dark:text-blue-200',
    topBadge: 'Vector Wizard',
  },
  {
    rank: 10,
    name: 'David Kim',
    username: 'david_k',
    institutionOrCountry: 'KAIST (South Korea)',
    streakDays: 18,
    scoreXp: 1920,
    rankChange: 0,
    avatarBg: 'bg-amber-600/20 text-amber-800 dark:text-amber-200',
    topBadge: 'Triton Kernel Specialist',
  },
];

export const ACHIEVEMENT_BADGES: AchievementBadge[] = [
  {
    id: 'badge-rag-master',
    name: 'RAG Master',
    category: 'Systems Architecture',
    icon: '🎖️',
    description: 'Flawless assembly of the RAG Pipeline in the Bubble Game with hybrid search and reranker.',
    requirement: 'Complete the RAG Master Bubble Game challenge with 0 errors.',
    isUnlocked: true,
    unlockedAt: 'Yesterday',
    recruiterValue: 'Elite',
  },
  {
    id: 'badge-cuda-ninja',
    name: 'NVIDIA TensorRT Specialist',
    category: 'Hardware Acceleration',
    icon: '🟢',
    description: 'Mastery over CUDA memory hierarchies, TensorRT-LLM engines, and FP8 quantization.',
    requirement: 'Score > 8.0 on the NVIDIA Company Pack Capstone.',
    isUnlocked: true,
    unlockedAt: '2 days ago',
    recruiterValue: 'Elite',
  },
  {
    id: 'badge-agent-architect',
    name: 'Agent Architect',
    category: 'Agent Systems',
    icon: '🤖',
    description: 'Proven ability to build ReAct agentic loops with strict JSON schema tool validation.',
    requirement: 'Complete the OpenAI Pack and pass the Tool Calling Error Hunter challenge.',
    isUnlocked: false,
    recruiterValue: 'Distinguished',
  },
  {
    id: 'badge-flame-streak',
    name: '7-Day Flame Streak',
    category: 'Consistency & Dedication',
    icon: '🔥',
    description: 'Answered the Daily Voice Coach question 7 consecutive mornings at 8:00 AM.',
    requirement: 'Maintain a 7-day daily speaking streak.',
    isUnlocked: false,
    recruiterValue: 'High',
  },
  {
    id: 'badge-vector-wizard',
    name: 'Vector Wizard',
    category: 'Data & Retrieval',
    icon: '🔮',
    description: 'Top evaluation on pgvector HNSW vs IVFFlat indexing tradeoffs under sub-50ms constraints.',
    requirement: 'Solve the AI Decision Simulator Vector Mission with optimal rating.',
    isUnlocked: true,
    unlockedAt: '3 days ago',
    recruiterValue: 'High',
  },
  {
    id: 'badge-prompt-titan',
    name: 'Prompt Titan',
    category: 'LLM Steering',
    icon: '⚡',
    description: 'Zero format errors in structured JSON output generation and safety guardrail prompts.',
    requirement: 'Complete Error Hunter on Structured Outputs without hint.',
    isUnlocked: false,
    recruiterValue: 'High',
  },
];
